name: Fhi.VersionApiClient.Nuget

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: 8.0.x

      - name: Pack
        run: dotnet pack /p:ContinuousIntegrationBuild=true --output package 

      - name: Publish nupkg and snupkg to NuGet.org
        run: |
          foreach($file in (Get-ChildItem -Path package -Recurse -Include "*.nupkg")) {
              Write-Host "Publishing nupkg and snupkg:: " $file.FullName
              dotnet nuget push $file.FullName --api-key "${{ secrets.NUGET_ORG_FHI_PUBLISH }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
